### ISSUE TITLE
ChangeTrustOperationBuilder(asset, '922337203685.4775807') fails on web

### ISSUE THREAD

**Issue by rinat-enikeev** [Soneso/stellar_flutter_sdk#96] opened 2024-06-23 19:27 UTC
Web. The following code. 

```dart
AccountResponse account =
        await stellarSDK.accounts.account(keyPair.accountId);

    Transaction transaction = TransactionBuilder(account)
        .addOperation(
            ChangeTrustOperationBuilder(predefinedAsset, '922337203685.4775807')
                .build())
        .build();

    transaction.sign(keyPair, kDebugMode ? Network.TESTNET : Network.PUBLIC);

    SubmitTransactionResponse response =
        await stellarSDK.submitTransaction(transaction);
 ```
 
 Produces the folowing transaction: 
 
 
<img width="480" alt="Screenshot 2024-06-23 at 22 26 27" src="https://github.com/Soneso/stellar_flutter_sdk/assets/722716/a5e88f21-2f5a-4438-aeb1-b4838061ac0b">

Note: `limit: -922,337,203,685.4775808 (raw: -9223372036854775808)`

**Comment by christian-rogobete** [comment] 2024-06-25 13:44
Hello @rinat-enikeev,

thank you for adding this issue. Unfortunately, I cannot reproduce it. I have built a test case that you can find [here](https://github.com/Soneso/stellar_flutter_sdk/blob/2ea794b533bd3b61764d54de65ff66a7990b3bf7/test/account_test.dart#L86).

```dart
  test('test max trust amount', () async {

    final issuerAccountId = KeyPair.random().accountId;
    final trustingKeyPair = KeyPair.random();
    final trustingAccountId = trustingKeyPair.accountId;

    await FriendBot.fundTestAccount(issuerAccountId);
    await FriendBot.fundTestAccount(trustingAccountId);

    final trustingAccount = await sdk.accounts.account(trustingAccountId);

    final myAsset = AssetTypeCreditAlphaNum12('AOXYGEN', issuerAccountId);

    final changeTrustOp = ChangeTrustOperationBuilder(myAsset, '922337203685.4775807').build();

    final transaction = new TransactionBuilder(trustingAccount).addOperation(changeTrustOp).build();

    transaction.sign(trustingKeyPair, Network.TESTNET);

    print('TX XDR: ${transaction.toEnvelopeXdrBase64()}');

    final response = await sdk.submitTransaction(transaction);
    assert(response.success);

  });
```
It prints following xdr:

`AAAAAgAAAAAxgpk1bmxkv9j0qXMj+yQmBBwduEfwmkVDU43WfSKL5QAAAGQAA28NAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAGAAAAAkFPWFlHRU4AAAAAAAAAAAB45zZk4+1YTSmLLK+QynEWM1M1VrlxExAhqgXmZKtWDH//////////AAAAAAAAAAF9IovlAAAAQH/P08+n2vsgNzB4vM2hjeWCZA7Iul3QDElio9mRHhTKyeqMfe4X9UR+5y28x0fCgOZGZHGtcKivR1yTucOFnAg=`

If I insert it into Stellar Lab:

![Screenshot 2024-06-25 at 15 39 59](https://github.com/Soneso/stellar_flutter_sdk/assets/35729606/07a94d9c-8ebc-443f-a22f-3a8076ef4ea6)

Could you please run the test on your device? Which device did you test it on?

**Comment by rinat-enikeev** [comment] 2024-06-28 17:25
Hey @christian-rogobete, thank you! 

Just in case you need an example, you can clone this [repository](https://github.com/rinat-enikeev/sfsdk_web_issue) and run on web (chrome). 

The code is [simple](https://github.com/rinat-enikeev/sfsdk_web_issue/blob/main/lib/main.dart#L34-L55).

**Comment by christian-rogobete** [comment] 2024-06-29 07:29
Hey @rinat-enikeev, thank you for providing example code. I already fixed the issue in this [commit](https://github.com/Soneso/stellar_flutter_sdk/commit/1e8852224691ad0a02b443d78e56fc0e5c2ae88e) and the fix will be available in the next release. This improvement will also allow large amounts on web for many other operations such as, `create_account`, `payment`, `path_payment_strict_send`, `path_payment_strict_receive`, `manage_sell_offer`, `manage_buy_offer`, `create_passive_sell_offer`, `clawback`, `create_claimable_balance`, `liquidity_pool_deposit`, `liquidity_pool_withdraw`.  However, the sdk will still not officially support web. I am planning another release for official web support in the coming months.

**Comment by christian-rogobete** [comment] 2024-07-01 09:45
Hello @rinat-enikeev, this issue has been fixed in [release 1.8.2](https://github.com/Soneso/stellar_flutter_sdk/releases/tag/1.8.2)

**Closed by christian-rogobete** 2024-07-01 09:45 UTC

**Comment by rinat-enikeev** [comment] 2024-07-01 21:22
Thanks @christian-rogobete, can't find `donate` button though :) 

If it is helpful, I would report that with `1.8.2` stopped working on `web` for another reason: 

`_sequenceNumber` is not being incremented for first account transaction: 

```json
{"transaction":"tx_bad_seq"}
```

This works in local debug mode, but doesn't work in release and profile on prod. 

<img width="1024" alt="Screenshot 2024-07-02 at 00 15 45" src="https://github.com/Soneso/stellar_flutter_sdk/assets/722716/06aa7692-e55f-4e7c-9cc8-ab3b16b2cf75">


[staging website](https://founders-game.web.app/). 

If you want I can create another issue and provide more details. Thanks!

**Comment by christian-rogobete** [comment] 2024-07-01 22:49
Hello @rinat-enikeev, thank you! It would be great and helpful if you can add a new issue with a description on how to reproduce the sequence number issue.
